[workspace.package]
name = "picotracker"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

[workspace]
members = [
    "rp2040",
    "gpslib",
    "modbus_master",
    "envconst"
]
resolver = "2"
